### PR TITLE
[Fix] Reformats signed URL to allow for bucket names that contain periods

### PR DESCRIPTION
**Pull request by LettItBrew**
We have encountered a bug when generating signed URLs for buckets that contain periods, such as `example.example.com`.  The current solution uses the deprecated subdomain approach for building the host for signed urls. IE  `{bucket-name}.storage.googleapis.com`  This produces a TLS common name error.

According to the [documentation](https://cloud.google.com/storage/docs/buckets#naming), buckets containing periods are valid.

This change reformats the host and canonical_uri to use the new standard format of `{storage.googleapis.com/{bucket-name}`.  See [documentation](https://cloud.google.com/storage/docs/access-control/signed-urls#example).

I have manually verified this change locally.  However, I did not include a test in this pull request because I was unable to run integration tests due to not having the required GCP credentials. Please let me know if there is a way for me to properly test this change.

### CODE REVIEW

**Comment by LettItBrew** [comment]
Hello! @TheKevJames @all2ham @jonathan-johnston 

Is there any chance one of you can review this change?

**Comment by LettItBrew** [comment]
Can someone manually trigger integration tests please? 🙂

**Comment by LettItBrew** [comment]
This PR duplicates https://github.com/talkiq/gcloud-aio/pull/602 so I'm closing this one.

**Comment by TheKevJames** [comment]
Just noting here that #602 just got merged and will be included in the next release. Thanks for the contribution nonetheless!

**Pull request closed without merging**
