### PR TITLE
Storage streams

### PR DESCRIPTION
**Pull request by JensMadsen**
#44 storage upload handle streams

### CODE REVIEW

**Comment by JensMadsen** [comment]
#44

**Comment by TheKevJames** [comment]
@JensMadsen it looks like this PR includes all the changes from your other PR. As that's the case, I'd rather avoid reviewing it until we get the other one merged so this changeset is a bunch smaller. If it can be reviewed separately, feel free to remove the changes from the other PR so I can review just this chunk. If it has to depend on the other PR, then we can just wait.

**Comment by JensMadsen** [comment]
@TheKevJames I depends on the resumableupload PR :-)

**Comment by JensMadsen** [comment]
> @JensMadsen ping for a friendly reminder on this and [#46 (comment)](https://github.com/talkiq/gcloud-aio/pull/46#issuecomment-444358294)

@TheKevJames Sorry about the silence. I ended up using node instead. Turned out to be easier in perticular because I build a graphql thing :-) I will not have time to look at this pr in the near future. Sorry

**Comment by TheKevJames** [comment]
@JensMadsen no problem. If you don't mind, then, I'll take over this PR for ya. Thanks again for the contributions! They were much appreciated :)

**Comment by TheKevJames** [comment]
Taking over the PR at #65. Thanks again Jens!

For future linking: the part of the PR which applies to storage streams can be found [here](https://github.com/talkiq/gcloud-aio/compare/fb6d4b0f40aee86539b3f2101ff724430f969671...444ba32f8dded02e2c3a6aafd2a41a7715b730e6).

**Pull request closed without merging**
