### PR TITLE
feat(taskqueue): add timeout argument and remove retries

### PR DESCRIPTION
**Pull request by javierdialpad**
Adding timeout argument and removing backoff decorator  from taskqueue methods to be consistent with the other lib modules, and let the lib user handle timeouts/retries.

Motivated by https://dialpad.atlassian.net/browse/INFRA-1849.

Following this change, I will adapt https://github.com/dialpad/firespotter/tree/master/common/lib3/taskqueue_helper to handle timeouts and retries. Does the module have other users we should worry about?

### CODE REVIEW

**Review by shaundialpad — APPROVED** [review]
Makes sense to me! Seems appropriate to have this configured by the user, and matches our other expectations throughout `gcloud-aio`. Should be able to remove this from the library dependencies as well.

The failing tests seem unrelated...

**Comment by javierdialpad** [comment]
> Makes sense to me! Seems appropriate to have this configured by the user, and matches our other expectations throughout `gcloud-aio`. Should be able to remove this from the library dependencies as well.
>
You mean the backoff dependency? It's still being used: https://github.com/talkiq/gcloud-aio/blob/597ca5bebc1f2e858ef6410a98aac715ef4c0378/auth/gcloud/aio/auth/token.py#L258

> 
> The failing tests seem unrelated...
>
All right, thanks @shaundialpad!

**Comment by shaundialpad** [comment]
> You mean the backoff dependency? It's still being used:
> 
> https://github.com/talkiq/gcloud-aio/blob/597ca5bebc1f2e858ef6410a98aac715ef4c0378/auth/gcloud/aio/auth/token.py#L258

Oh I meant it's not being used in `gcloud-aio-taskqueue`

**Review by shaundialpad — COMMENTED** [review]
Also it seems your fork is far behind talkiq:master which might be causing the failing tests.

**Comment by javierdialpad** [comment]
> > You mean the backoff dependency? It's still being used:
> > https://github.com/talkiq/gcloud-aio/blob/597ca5bebc1f2e858ef6410a98aac715ef4c0378/auth/gcloud/aio/auth/token.py#L258
> 
> Oh I meant it's not being used in `gcloud-aio-taskqueue`

Ohh dependencies are per-module. Ok will remove it!

**Comment by javierdialpad** [comment]
> > You mean the backoff dependency? It's still being used:
> > https://github.com/talkiq/gcloud-aio/blob/597ca5bebc1f2e858ef6410a98aac715ef4c0378/auth/gcloud/aio/auth/token.py#L258
> 
> Oh I meant it's not being used in `gcloud-aio-taskqueue`
>
Ohh dependencies are per-module. Ok will remove it!

**Comment by javierdialpad** [comment]
Removed the backoff dependency from taskqueue and i'm not being able to get the poetry lock right. I just did:
```
poetry self update 1.1.9
poetry remove backoff
poetry lock
```

But still getting this error https://app.circleci.com/pipelines/github/talkiq/gcloud-aio/2353/workflows/98f0a245-6540-4a2c-80f2-97cd2f244dc5/jobs/77790/parallel-runs/0/steps/0-110.

Any ideas? @shaundialpad @TheKevJames

**Comment by shaundialpad** [comment]
> Removed the backoff dependency from taskqueue and i'm not being able to get the poetry lock right. I just did:
> 
> ```
> poetry self update 1.1.9
> poetry remove backoff
> poetry lock
> ```
> 
> But still getting this error https://app.circleci.com/pipelines/github/talkiq/gcloud-aio/2353/workflows/98f0a245-6540-4a2c-80f2-97cd2f244dc5/jobs/77790/parallel-runs/0/steps/0-110.
> 
> Any ideas? @shaundialpad @TheKevJames

Hmm you might want to try updating poetry to `1.3.x`. Not sure exactly what is causing this issue though, @TheKevJames might know more.

**Comment by javierdialpad** [comment]
> > Removed the backoff dependency from taskqueue and i'm not being able to get the poetry lock right. I just did:
> > ```
> > poetry self update 1.1.9
> > poetry remove backoff
> > poetry lock
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But still getting this error https://app.circleci.com/pipelines/github/talkiq/gcloud-aio/2353/workflows/98f0a245-6540-4a2c-80f2-97cd2f244dc5/jobs/77790/parallel-runs/0/steps/0-110.
> > Any ideas? @shaundialpad @TheKevJames
> 
> Hmm you might want to try updating poetry to `1.3.x`. Not sure exactly what is causing this issue though, @TheKevJames might know more.
>
Was using 1.3.2 initially, i think. Tried downgrading to match the version used on ci/cd 

image

**Comment by shaundialpad** [comment]
@javierdialpad Ah so apparently our CI doesn't play nicely with external forks. I'll make a new PR in a bit with your changes and appropriate credit, sorry about the confusion!

**Comment by javierdialpad** [comment]
> @javierdialpad Ah so apparently our CI doesn't play nicely with external forks. I'll make a new PR in a bit with your changes and appropriate credit, sorry about the confusion!
>
Ohh. I knew the integration tests would fail due to auth not working for me. But could poetry also be an issue? All right let me know if you manage to open a new one. Thanks!

**Comment by TheKevJames** [comment]
Ah, sorry, we're currently having to pin to `poetry==1.1.9` to maintain support for Python2.7 (hopefully we can nuke that soon!). I'll write up something into the contribution guide to make that clear.

**Comment by TheKevJames** [comment]
Pushed to [an internal branch](https://github.com/talkiq/gcloud-aio/commits/taskqueue-timeout) and [running tests](https://app.circleci.com/pipelines/github/talkiq/gcloud-aio/2363/workflows/f0b03f2e-ddf1-48f9-8a2c-12b3f5a34d00) with an [updated lockfile](https://github.com/talkiq/gcloud-aio/commit/0ce1042dbaab40bc03316bfc275c4fa8847e3459).

(also included a version bump so we can release this right away including the [unrelated breaking change already on `master`](https://github.com/talkiq/gcloud-aio/commit/ed50d39ecde6c2700a9fea73d2cc767a9dd00001))

**Comment by javierdialpad** [comment]
> Ah, sorry, we're currently having to pin to `poetry==1.1.9` to maintain support for Python2.7 (hopefully we can nuke that soon!). I'll write up something into the contribution guide to make that clear.
>
Yeah, tried with that version too. Even did a clean install, deleted cached, etc, but no luck.

All right I think I'll desist from trying to remove the backoff dependency and merge just the required changes.

**Comment by TheKevJames** [comment]
[Merged](https://github.com/talkiq/gcloud-aio/commit/1d000f244a2177ac720b8cb137b197694c516b68) via the branch I mentioned and getting v6.0.0 released shortly with this change included. Thanks!

**Comment by javierdialpad** [comment]
> [Merged](https://github.com/talkiq/gcloud-aio/commit/1d000f244a2177ac720b8cb137b197694c516b68) via the branch I mentioned and getting v6.0.0 released shortly with this change included. Thanks!
>
Awesome, thanks!!

**Pull request closed without merging**
