### PR TITLE
chore(bq): bump bigquery from 5.0.0 -> 5.1.0

### PR DESCRIPTION
**Pull request by jonathan-johnston**
Releases new feature https://github.com/talkiq/gcloud-aio/pull/231

### CODE REVIEW

**Review by amartsinovich-dialpad — APPROVED** [review]
Could be bundled with https://github.com/talkiq/gcloud-aio/pull/232 But won't hurt releasing it earlier 👍

**Review by TheKevJames — APPROVED** [review]

**Comment by jonathan-johnston** [comment]
@amartsinovich-dialpad I can hold off releasing this until #232 is in and can rebase off `master`. But isn't #232 an interface-breaking change?

**Comment by amartsinovich-dialpad** [comment]
# 232:
1. `Job(job_id: str)` -> `Job(job_id: Optional[str]`
2. NEW `Job#insert_via_query`
3. DEPRECATED (but still working!) `Table#insert_via_query`
4. Added `use_legacy_sql: bool = True` to `Table#insert_via_query` as optional last argument

I have to confess I don't know the formal definition of breaking changes, but all those seem backwards compatible?

**Comment by TheKevJames** [comment]
Nah, I don't think any of those are interface-breaking. (1) is strictly additive (ie. adding the `None` case), so all should be well there.

Mind, that doesn't mean we need to hold off here, necessarily. #232 can always just become `v5.2.0` instead /shrug

**Comment by jonathan-johnston** [comment]
My bad! I didn't see that the function was deprecated, I thought it was removed entirely. Definitely not breaking changes then!

**Comment by jonathan-johnston** [comment]
Rebased on `master` to pick up #232

**Pull request merged**
