### PR TITLE
fix(datastore): allow microsecond resolution timestamp values

### PR DESCRIPTION
**Pull request by snstanton**
Slice the date string to drop the nanoseconds and trailing 'Z'.

### CODE REVIEW

**Comment by snstanton** [comment]
I didn't change anything in test-pubsub, so I'm reasonably confident this failure has nothing to do with my change.

**Comment by snstanton** [comment]
Hmm.  I'm finding more corner cases, so I'm going to close this request until I get more test coverage.

**Comment by TheKevJames** [comment]
@snstanton looking forward to seeing this, if you figure out those edge-cases :) It would be great to get that hooked into the integration tests, as well, since it looks like this will depend heavily on the Google API responses!

wrt the Pubsub tests, it looks like the guard against running that test for external contributors is still having issues -- you can go ahead and ignore that. Theoretically, [this block](https://github.com/talkiq/gcloud-aio/blob/6a120024e8bca0f18ad8c404b89a637705e3fdac/pubsub/noxfile.py#L7-L31) is supposed to be `session.skip`ing those tests (since we don't yet have GCP creds that we can share with external contributors), but it looks like I'll need to rework that...

**Comment by snstanton** [comment]
Ok, I think I've got the additional cases sorted out.  It turns out all of msec, usec, and nsec were used at one time or another.  I guess that's what happens when you've been using datastore since the earliest days of appengine.

I'm not sure how to run the integration tests, so I'm hesitant to add anything there.

**Pull request merged**
