### PR TITLE
remove dependency on `typing`

### PR DESCRIPTION
**Pull request by mozbhearsum**
According to the documentation of "typing":

> NOTE: in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT. To get a newer version of the typing module in Python 3.5 or later, you have to upgrade to a newer Python (bugfix) version. For example, typing in Python 3.6.0 is missing the definition of ‘Type’ – upgrading to 3.6.2 will fix this.

Given that, and that `gcloud-aio-auth` only supports Python 3.6 and up, it looks like this dependency can be dropped? It might be best to bump `python_requires` to 3.6.2 as well (or perhaps needing to support 3.6.0 makes this unfixable for the moment).

### CODE REVIEW

**Comment by TheKevJames** [comment]
Hi @mozbhearsum! We appreciate the contribution; you're definitely correct for the `gcloud-aio-*` family of projects in this repo: however, we'd like to avoid dropping support for versions 3.6.0 and 3.6.1 if at all possible.

I think the `extras_require` field in `auth/setup.py` might help us here -- could we add something like:
```python
setup(
    # SNIP...
    extras_require={':python_version < "3.6.2"': ['typing']}
    # SNIP...
```
to get that to work? I think that should obviate the need for the `gcloud-rest` specific changes as well, so `gcloud-rest` installed on a never version of python wouldn't get the noop `typing` install either :)

**Comment by mozbhearsum** [comment]
> Hi @mozbhearsum! We appreciate the contribution; you're definitely correct for the `gcloud-aio-*` family of projects in this repo: however, we'd like to avoid dropping support for versions 3.6.0 and 3.6.1 if at all possible.
> 
> I think the `extras_require` field in `auth/setup.py` might help us here -- could we add something like:
> 
> ```python
> setup(
>     # SNIP...
>     extras_require={':python_version < "3.6.2"': ['typing']}
>     # SNIP...
> ```
> 
> to get that to work? I think that should obviate the need for the `gcloud-rest` specific changes as well, so `gcloud-rest` installed on a never version of python wouldn't get the noop `typing` install either :)

Hm, I didn't know you could do that in `extra_requires`! I'll give it a shot.

**Comment by mozbhearsum** [comment]
So I tried this in https://github.com/mozbhearsum/gcloud-aio/commit/966508f1ac966400ca215a428702209adce0115f, but as far as I can tell `extras_requires` doesn't respect python versions. For example:
```
root@98ba8184e918:/gcloud-aio/auth# cat requirements.txt 
aiohttp>=2.0.0,<4.0.0
backoff>=1.0.0,<2.0.0
cryptography>=2.0.0,<3.0.0
future>=0.17.0,<0.18.3
pyjwt>=1.5.3,<2.0.0
# requests>=2.20.0,<2.23.0
six>=1.11.0,<2.0.0
root@98ba8184e918:/gcloud-aio/auth# cat setup.py
import os

import setuptools


PACKAGE_ROOT = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(PACKAGE_ROOT, 'README.rst')) as f:
    README = f.read()

with open(os.path.join(PACKAGE_ROOT, 'requirements.txt')) as f:
    REQUIREMENTS = [r.strip() for r in f.readlines()]


setuptools.setup(
    name='gcloud-aio-auth',
    version='3.1.0',
    description='Python Client for Google Cloud Auth',
    long_description=README,
    namespace_packages=[
        'gcloud',
        'gcloud.aio',
    ],
    packages=setuptools.find_packages(exclude=('tests',)),
    install_requires=REQUIREMENTS,
    extras_require={':python_version < "3.6.2"': ['typing']},
    python_requires='>= 3.6',
    author='Vi Engineering',
    author_email='voiceai-eng@dialpad.com',
    url='https://github.com/talkiq/gcloud-aio',
    platforms='Posix; MacOS X; Windows',
    include_package_data=True,
    zip_safe=False,
    license='MIT License',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Topic :: Internet',
    ],
)
root@98ba8184e918:/gcloud-aio/auth# python -V
Python 3.6.2
root@98ba8184e918:/gcloud-aio/auth# python setup.py install 2>&1 | grep typing
Searching for typing
Reading https://pypi.python.org/simple/typing/
Downloading https://files.pythonhosted.org/packages/67/b0/b2ea2bd67bfb80ea5d12a5baa1d12bda002cab3b6c9b48f7708cd40c34bf/typing-3.7.4.1.tar.gz#sha256=91dfe6f3f706ee8cc32d38edbbf304e9b7583fb37108fef38229617f8b3eba23
Best match: typing 3.7.4.1
Processing typing-3.7.4.1.tar.gz
Writing /tmp/easy_install-o0pyltf2/typing-3.7.4.1/setup.cfg
Running typing-3.7.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-o0pyltf2/typing-3.7.4.1/egg-dist-tmp-dufo_wxl
Moving typing-3.7.4.1-py3.6.egg to /usr/local/lib/python3.6/site-packages
Adding typing 3.7.4.1 to easy-install.pth file
Installed /usr/local/lib/python3.6/site-packages/typing-3.7.4.1-py3.6.egg
```

**Comment by TheKevJames** [comment]
Ah, looks like I got the syntax entirely wrong (see [PEP-508](https://www.python.org/dev/peps/pep-0508/)). tl;dr is I think all we need to do is update the requirements file line for `typing` to read `typing>=3.7.4.1,<4.0.0;python_full_version<"3.6.2"`:
```bash
~ » mkdir -p /tmp/testdeps
~ » cd /tmp/testdeps
/t/testdeps » echo "import setuptools
setuptools.setup(
    name='testapp',
    version='1.2.3',
    description='Testapp for conditional dependencies',
    packages=[],
    install_requires=[
        'typing;python_full_version<\"3.6.2\"',
    ],
)" > setup.py

/t/testdeps » python3.5 -m venv venv5
/t/testdeps » source venv5/bin/activate
(venv5) /t/testdeps » python --version
Python 3.5.9
(venv5) /t/testdeps » pip install -e .
Obtaining file:///private/tmp/testdeps
Collecting typing; python_full_version < "3.6.2" (from testapp==1.2.3)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/fe/2e/b480ee1b75e6d17d2993738670e75c1feeb9ff7f64452153cf018051cc92/typing-3.7.4.1-py3-none-any.whl
Installing collected packages: typing, testapp
  Running setup.py develop for testapp
Successfully installed testapp typing-3.7.4.1
You are using pip version 9.0.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv5) /t/testdeps » deactivate

/t/testdeps » python3.6 -m venv venv6
/t/testdeps » source venv6/bin/activate
(venv6) /t/testdeps » python --version
Python 3.6.10
(venv6) /t/testdeps » pip install -e .
Obtaining file:///private/tmp/testdeps
Installing collected packages: testapp
  Running setup.py develop for testapp
Successfully installed testapp
You are using pip version 18.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by mozbhearsum** [comment]
@TheKevJames - I think the remaining failures here are actually test issues -- nox appears to be running against python3 even for tests against python2. It's not clear to me what the best way to fix that is.

**Comment by vmarkovtsev** [comment]
Just noting that there is a big practical value in this PR: I am getting `AttributeError: type object 'Callable' has no attribute '_abc_registry'` inside the installed `typing` package on py3.7-3.8 and it forces me to additionally uninstall `typing` in my `Dockerfile` and describe the workaround in all the README-s.

**Comment by vmarkovtsev** [comment]
We are hitting https://github.com/pypa/pip/issues/6384 here.

The following `Dockerfile` reproduces the problem:

```dockerfile
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y python2 curl && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python2 get-pip.py && \
    echo 'typing>=3.7.4.1,<4.0.0; python_full_version<"3.6.2"' > r && \
    pip install -r r
```

You should see

```
Ignoring typing: markers 'python_full_version < "3.6.2"' don't match your environment
```

**Comment by vmarkovtsev** [comment]
@mozbhearsum I think I found a hack that resolves this problem. Try this:

```
typing>=3.7.4.1,<4.0.0; python_version<"3.6" or python_full_version<"3.6.2"
```

1. On Python 2.7, the first condition is True while the second is False (IDK why!!!), so `typing` installs.
2. On Python 3.6.0 or 3.6.1, the first condition is False while the second is True, so `typing` installs.
3. On Python 3.6.2+ both conditions are False and `typing` does not install.

I didn't know you can `or` multiple checks. Apparently, you can :smile:

**Comment by mozbhearsum** [comment]
> Just noting that there is a big practical value in this PR: I am getting `AttributeError: type object 'Callable' has no attribute '_abc_registry'` inside the installed `typing` package on py3.7-3.8 and it forces me to additionally uninstall `typing` in my `Dockerfile` and describe the workaround in all the README-s.

Yeah, this my motivation as well. Right now, this bug is preventing me from updating `pip-tools` in a project.



> @mozbhearsum I think I found a hack that solves this problem. Try this:
> 
> ```
> typing>=3.7.4.1,<4.0.0; python_version<"3.6" or python_full_version<"3.6.2"
> ```
> 
>     1. On Python 2.7, the first condition is True while the second is False (IDK why!!!), so `typing` installs.
> 
>     2. On Python 3.6.0 or 3.6.1, the first condition is False while the second is True, so `typing` installs.
> 
>     3. On Python 3.6.2+ both conditions are False and `typing` does not install.
> 
> 
> I didn't know you can `or` multiple checks. Apparently, you can smile

Are you doing this in the requirements file of your project that also depends on `gcloud-aio`?

**Comment by TheKevJames** [comment]
Catching up on this issue -- TIL about being able to use `or` in the version limiting field, nice find @vmarkovtsev! If that helps avoid pypa/pip#6384, sounds great to me. @mozbhearsum could you update this PR to include that fallback?

As for the `nox` tests, it seems like theses are real errors. Grabbbing the logs from [a random failing job](https://app.circleci.com/pipelines/github/talkiq/gcloud-aio/723/workflows/4855067e-c8ad-4e84-9879-981bc51441a7/jobs/14117/steps):
```
nox -f rest/taskqueue/noxfile.py 
nox > Running session unit_tests-2.7
nox > Creating virtual environment (virtualenv) using python2.7 in .nox/unit_tests-2-7
nox > pip install future
nox > pip install pytest pytest-cov ../auth/
nox > pip install -e .
nox > py.test --quiet --cov=gcloud.rest.taskqueue --cov=tests.unit --cov-append --cov-report= tests/unit

==================================== ERRORS ====================================
__________________ ERROR collecting tests/unit/utils_test.py ___________________
ImportError while importing test module '/root/project/rest/taskqueue/tests/unit/utils_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/utils_test.py:7: in <module>
    import gcloud.rest.taskqueue.utils as utils  # pylint: disable=unused-import
gcloud/rest/taskqueue/__init__.py:10: in <module>
    from gcloud.rest.taskqueue.queue import PushQueue
gcloud/rest/taskqueue/queue.py:13: in <module>
    from typing import Any
E   ImportError: No module named typing

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!

1 error in 0.34 seconds
nox > Command py.test --quiet --cov=gcloud.rest.taskqueue --cov=tests.unit --cov-append --cov-report= tests/unit failed with exit code 2
nox > Session unit_tests-2.7 failed.
```

So it looks like `typing` is not being installed for the `gcloud-rest` variation of these packages under python 2.7?

**Comment by vmarkovtsev** [comment]
> Are you doing this in the requirements file of your project that also depends on gcloud-aio

Nope, I am doing this in the very same place this PR is doing.

> So it looks like typing is not being installed for the gcloud-rest variation of these packages under python 2.7?

Yep. `python_full_version` behaves weird on 2.7, hence the `or`.

**Comment by mozbhearsum** [comment]
I think this might finally be ready, @TheKevJames? :joy:

**Comment by TheKevJames** [comment]
Looks like it's working wonderfully now. Thanks @mozbhearsum and @vmarkovtsev for all the investigation here!

**Comment by TheKevJames** [comment]
Releasing this as v3.2.2 as soon as CI finishes!

**Pull request merged**
